### ISSUE TITLE
Docker bug of infinit number of "..."

### ISSUE THREAD

**Issue by lovesmall** [Oslandia/workshop-3d#2]
Hi Oslandia team,

Thanks for such a nice workshop. I'm new to the GIS area, and very impressed by the 3D city on the webGL. Just wondering have you found the solution for the mysterious Docker bug?

I followed the workshop on a fresh copy of Ubuntu and but faced this Docker bug. I have to rebuild both pggis and 3dgis locally. They both finished but with some errors. Still working on it.

**Comment by vpicavet** [comment]
Hi,
It should be solved with latest image of docker pggis. Be sure to have latest docker from their repos and clean all containers and images before rerunning a build.
Vincent

**Comment by lovesmall** [comment]
Thanks Vincent.

I rebuild and can successfully run the workshop.
